name: Anylinux-AppImage (Nightly)
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# comment these two out to enable nightly builds, This sets the variable DEVEL_RELEASE=1 for  #
# get-dependencies.sh to make a nightly release, this will make a release with 'nightly' tag  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  schedule:
    - cron: "0 7 1/5 * *" # We default to rebuilding nightly every 2 days, change this to your liking
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          # comment out these 3 lines if aarch64 is not wanted
          - runs-on: ubuntu-24.04-arm
            name: Build AppImage
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@0964f2258d6c93d1391359978dde081fd8b3c6af # v2
      - name: Install Dependencies
        run: DEVEL_RELEASE=1 /bin/sh ./get-dependencies.sh
      - name: Make AppImage
        run: DEVEL_RELEASE=1 /bin/sh ./make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          pattern: AppImage-*
          merge-multiple: true
        continue-on-error: true
      - name: Release Nightly AppImage
        uses: pkgforge-dev/make-nightly-appimage-release@17cbe90fc0796286e424619a54a82a3a880efe4c # v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
